# Material do curso de nivelamento em Deep Learning do professor Edson M. Takashi (FACOM - UFMS)

In [1]:
import nltk
nltk.download('machado')

[nltk_data] Downloading package machado to /root/nltk_data...


True

In [2]:
from nltk.corpus import machado

In [3]:
text=machado.raw()

In [4]:
# let's look at the first 1000 characters
print(text[:1000])

Conto, Contos Fluminenses, 1870

Contos Fluminenses

Texto-fonte:

Obra Completa, Machado de Assis, vol. II,

Rio de Janeiro: Nova Aguilar, 1994.

Publicado originalmente pela
Editora Garnier, Rio de Janeiro, em 1870.

ÍNDICE

MISS DOLLAR

LUÍS
SOARES

A MULHER DE
PRETO

O
SEGREDO DE AUGUSTA

CONFISSÕES DE UMA VIÚVA MOÇA

LINHA
RETA E LINHA CURVA

FREI
SIMÃO

MISS
DOLLAR

ÍNDICE

Capítulo Primeiro

Capítulo II

Capítulo iii

Capítulo iv

Capítulo v

Capítulo vI

Capítulo vII

CAPÍTULO VIII

CAPÍTULO PRIMEIRO

Era conveniente ao romance que o leitor
ficasse muito tempo sem saber quem era Miss Dollar. Mas por outro lado,
sem a apresentação de Miss Dollar, seria o autor obrigado a longas
digressões, que encheriam o papel sem adiantar a ação. Não há hesitação
possível: vou apresentar-lhes Miss Dollar.

Se o leitor é rapaz e dado ao gênio
melancólico, imagina que Miss Dollar é uma inglesa pálida e delgada,
escassa de carnes e de sangue, abrindo à flor do rosto dois grandes olhos azuis
e sac

In [5]:
# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
print(''.join(chars))
print(vocab_size)

	
 !"$%&'()*+,-./0123456789:;=?ABCDEFGHIJKLMNOPQRSTUVWXYZ[]_`abcdefghijklmnopqrstuvwxyz…‘’“”–—œ ¡§ª«­°´º»½¿ÀÁÂÃÇÈÉÊËÍÓÔÕÚÛÜàáâãäçèéêëìíîïñòóôõöùúûü
147


In [6]:
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

print(encode("olá isso é um teste"))
print(decode(encode("olá isso é um teste")))

[75, 72, 124, 2, 69, 79, 79, 75, 2, 130, 2, 81, 73, 2, 80, 65, 79, 80, 65]
olá isso é um teste


In [7]:
itos

{0: '\t',
 1: '\n',
 2: ' ',
 3: '!',
 4: '"',
 5: '$',
 6: '%',
 7: '&',
 8: "'",
 9: '(',
 10: ')',
 11: '*',
 12: '+',
 13: ',',
 14: '-',
 15: '.',
 16: '/',
 17: '0',
 18: '1',
 19: '2',
 20: '3',
 21: '4',
 22: '5',
 23: '6',
 24: '7',
 25: '8',
 26: '9',
 27: ':',
 28: ';',
 29: '=',
 30: '?',
 31: 'A',
 32: 'B',
 33: 'C',
 34: 'D',
 35: 'E',
 36: 'F',
 37: 'G',
 38: 'H',
 39: 'I',
 40: 'J',
 41: 'K',
 42: 'L',
 43: 'M',
 44: 'N',
 45: 'O',
 46: 'P',
 47: 'Q',
 48: 'R',
 49: 'S',
 50: 'T',
 51: 'U',
 52: 'V',
 53: 'W',
 54: 'X',
 55: 'Y',
 56: 'Z',
 57: '[',
 58: ']',
 59: '_',
 60: '`',
 61: 'a',
 62: 'b',
 63: 'c',
 64: 'd',
 65: 'e',
 66: 'f',
 67: 'g',
 68: 'h',
 69: 'i',
 70: 'j',
 71: 'k',
 72: 'l',
 73: 'm',
 74: 'n',
 75: 'o',
 76: 'p',
 77: 'q',
 78: 'r',
 79: 's',
 80: 't',
 81: 'u',
 82: 'v',
 83: 'w',
 84: 'x',
 85: 'y',
 86: 'z',
 87: '\x85',
 88: '\x91',
 89: '\x92',
 90: '\x93',
 91: '\x94',
 92: '\x96',
 93: '\x97',
 94: '\x9c',
 95: '\xa0',
 96: '¡',
 97: '§',
 

In [8]:
# let's now encode the entire text dataset and store it into a torch.Tensor
import torch # we use PyTorch: https://pytorch.org
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000]) # the 1000 characters we looked at earier will to the GPT look like this

torch.Size([14840456]) torch.int64
tensor([ 33,  75,  74,  80,  75,  13,   2,  33,  75,  74,  80,  75,  79,   2,
         36,  72,  81,  73,  69,  74,  65,  74,  79,  65,  79,  13,   2,  18,
         25,  24,  17,   1,   1,  33,  75,  74,  80,  75,  79,   2,  36,  72,
         81,  73,  69,  74,  65,  74,  79,  65,  79,   1,   1,  50,  65,  84,
         80,  75,  14,  66,  75,  74,  80,  65,  27,   1,   1,  45,  62,  78,
         61,   2,  33,  75,  73,  76,  72,  65,  80,  61,  13,   2,  43,  61,
         63,  68,  61,  64,  75,   2,  64,  65,   2,  31,  79,  79,  69,  79,
         13,   2,  82,  75,  72,  15,   2,  39,  39,  13,   1,   1,  48,  69,
         75,   2,  64,  65,   2,  40,  61,  74,  65,  69,  78,  75,  27,   2,
         44,  75,  82,  61,   2,  31,  67,  81,  69,  72,  61,  78,  13,   2,
         18,  26,  26,  21,  15,   1,   1,  46,  81,  62,  72,  69,  63,  61,
         64,  75,   2,  75,  78,  69,  67,  69,  74,  61,  72,  73,  65,  74,
         80,  65,   2,  76,  

In [9]:
# Let's now split up the data into train and validation sets
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

In [10]:
block_size = 8
train_data[:block_size+1]

tensor([33, 75, 74, 80, 75, 13,  2, 33, 75])

In [11]:
x = train_data[:block_size]
y = train_data[1:block_size+1]
for t in range(block_size):
    context = x[:t+1]
    target = y[t]
    print(f"when input is {context} the target: {target}")

when input is tensor([33]) the target: 75
when input is tensor([33, 75]) the target: 74
when input is tensor([33, 75, 74]) the target: 80
when input is tensor([33, 75, 74, 80]) the target: 75
when input is tensor([33, 75, 74, 80, 75]) the target: 13
when input is tensor([33, 75, 74, 80, 75, 13]) the target: 2
when input is tensor([33, 75, 74, 80, 75, 13,  2]) the target: 33
when input is tensor([33, 75, 74, 80, 75, 13,  2, 33]) the target: 75


In [12]:
torch.manual_seed(1337)
batch_size = 4 # how many independent sequences will we process in parallel?
block_size = 8 # what is the maximum context length for predictions?

def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    return x, y

xb, yb = get_batch('train')
print('inputs:')
print(xb.shape)
print(xb)
print('targets:')
print(yb.shape)
print(yb)

print('----')

for b in range(batch_size): # batch dimension
    for t in range(block_size): # time dimension
        context = xb[b, :t+1]
        target = yb[b,t]
        print(f"when input is {context.tolist()} the target: {target}")

inputs:
torch.Size([4, 8])
tensor([[76, 78, 65, 65, 74, 64, 65, 81],
        [78, 73, 69, 80, 65, 13,  2, 82],
        [65, 67, 75, 63, 69, 61, 74, 80],
        [75, 73, 65, 81,  2, 65,  2, 75]])
targets:
torch.Size([4, 8])
tensor([[78, 65, 65, 74, 64, 65, 81,  2],
        [73, 69, 80, 65, 13,  2, 82, 69],
        [67, 75, 63, 69, 61, 74, 80, 65],
        [73, 65, 81,  2, 65,  2, 75, 72]])
----
when input is [76] the target: 78
when input is [76, 78] the target: 65
when input is [76, 78, 65] the target: 65
when input is [76, 78, 65, 65] the target: 74
when input is [76, 78, 65, 65, 74] the target: 64
when input is [76, 78, 65, 65, 74, 64] the target: 65
when input is [76, 78, 65, 65, 74, 64, 65] the target: 81
when input is [76, 78, 65, 65, 74, 64, 65, 81] the target: 2
when input is [78] the target: 73
when input is [78, 73] the target: 69
when input is [78, 73, 69] the target: 80
when input is [78, 73, 69, 80] the target: 65
when input is [78, 73, 69, 80, 65] the target: 13
when inpu

In [13]:
print(xb) # our input to the transformer

tensor([[76, 78, 65, 65, 74, 64, 65, 81],
        [78, 73, 69, 80, 65, 13,  2, 82],
        [65, 67, 75, 63, 69, 61, 74, 80],
        [75, 73, 65, 81,  2, 65,  2, 75]])


In [14]:
import torch
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(1337)

class BigramLanguageModel(nn.Module):

    def __init__(self, vocab_size):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

    def forward(self, idx, targets=None):

        # idx and targets are both (B,T) tensor of integers
        logits = self.token_embedding_table(idx) # (B,T,C)
        
        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss
    
    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # get the predictions
            logits, loss = self(idx)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)[0].tolist()))


torch.Size([32, 147])
tensor(5.6646, grad_fn=<NllLossBackward0>)
	É
/EiKÕ0'´-­Çô…Y3	Z­Rá–
1?f¡áe¡&rWC9[‘)Ff¡—œÉ:=üÇa	À­ÊtS¡qñf«8õ«¿Ûr«ç_AGa°à47õÔÔ¿ÇöïªeÛtÜ
Lâ°íœRP	


In [15]:
m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=100)

tensor([[  0,  31,  66, 110,  12,  18,  44, 102,  94,  96, 113, 131,  31,  14,
          39,  56,  74,  57,  46, 133,  56,  91,   6, 144,  66,  18,  71,   6,
          92,  42,  71, 123, 143,   9,  97, 135,  11, 132,  42,  29,  66, 123,
          32,  21,  63,  50,  81,  86,  77, 135,  64,  51,  23,  37, 133,  75,
          64,  94,  79, 127, 133,  25,   8,  26,  22,  74, 142,  55, 133,  21,
         119,  87, 104, 113,  65, 115, 136,  39,  89, 137,  71, 133,  70,  29,
          41, 109,  38, 109,  74, 131,  63,  55, 130,  71,  43,  21,  92, 107,
           9, 123,  25]])

In [16]:
idx = torch.zeros((1, 1), dtype=torch.long)

In [17]:
logits, loss = m.forward(idx)

In [18]:
logits.shape

torch.Size([1, 1, 147])

In [19]:
logits = logits[:, -1, :] # becomes (B, C)

In [20]:
logits.shape

torch.Size([1, 147])

In [21]:
probs = F.softmax(logits, dim=-1) # (B, C)

In [22]:
probs

tensor([[0.0043, 0.0033, 0.0025, 0.0014, 0.0067, 0.0037, 0.0093, 0.0038, 0.0051,
         0.0115, 0.0009, 0.0022, 0.0045, 0.0028, 0.0014, 0.0168, 0.0138, 0.0031,
         0.0048, 0.0094, 0.0005, 0.0059, 0.0159, 0.0065, 0.0041, 0.0008, 0.0011,
         0.0026, 0.0056, 0.0016, 0.0165, 0.0441, 0.0018, 0.0028, 0.0099, 0.0041,
         0.0042, 0.0112, 0.0011, 0.0027, 0.0022, 0.0014, 0.0062, 0.0008, 0.0011,
         0.0064, 0.0020, 0.0018, 0.0186, 0.0016, 0.0139, 0.0027, 0.0008, 0.0294,
         0.0569, 0.0006, 0.0153, 0.0008, 0.0082, 0.0029, 0.0078, 0.0166, 0.0179,
         0.0024, 0.0016, 0.0065, 0.0034, 0.0034, 0.0022, 0.0057, 0.0028, 0.0012,
         0.0267, 0.0021, 0.0045, 0.0072, 0.0009, 0.0089, 0.0041, 0.0045, 0.0433,
         0.0011, 0.0099, 0.0063, 0.0007, 0.0010, 0.0072, 0.0029, 0.0051, 0.0025,
         0.0058, 0.0017, 0.0024, 0.0023, 0.0013, 0.0024, 0.0007, 0.0009, 0.0030,
         0.0094, 0.0037, 0.0017, 0.0027, 0.0036, 0.0030, 0.0031, 0.0048, 0.0143,
         0.0040, 0.0456, 0.0

In [23]:
torch.argmax(probs).view([1,1])

tensor([[54]])

In [24]:
idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)

In [25]:
idx_next.shape

torch.Size([1, 1])

In [26]:
idx_next

tensor([[30]])

In [27]:
probs[0,idx_next]

tensor([[0.0165]], grad_fn=<IndexBackward0>)

In [28]:
torch.argmax(probs,dim=1)

tensor([54])

In [29]:
# get the predictions
logits, loss = m.forward(idx)
# focus only on the last time step
logits = logits[:, -1, :] # becomes (B, C)
# apply softmax to get probabilities
probs = F.softmax(logits, dim=-1) # (B, C)
# sample from the distribution
idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
# append sampled index to the running sequence
idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)

In [30]:
# create a PyTorch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

In [31]:
batch_size = 32
for steps in range(100): # increase number of steps for good results... 
    
    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = m(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

print(loss.item())


5.387226581573486


In [32]:
print(decode(m.generate(idx = torch.zeros((1, 1), dtype=torch.long), max_new_tokens=500)[0].tolist()))

	ãADúq%ËBèÂKUnnhôF$§3ËiêûMìpëâ(ub)x7zWçñmj4ZA:ñPx«EEçfW3Km½­óLkàâËûjËg§Ood½ ùëññÉ&…“¿)2cáÊcdY5À‘F:u(…–&½%o:ç¡UâùÃûzº…;e¿ÓÚT`ÂÈ0»a-CäËëñA1?œ§¿sIeõKm*mö5.»ìWCÈl(È´º…àO­â”œ`0ÛRÓÁ½ó?Nuz69ü?œíü`àVàêA´–8NB 87ÔY–Ó-oRf——4¡qJúUPb]ËuM'“*2KñM6*—K-qûOY2º'äâ=ç K‘Ç`;È] ÕyÂIcTü,ízADàQ6W26òTckMAS”*/lÔ Ü	Ú,äÚ'/p7X:´Õ$Aî°sop´%TFÃ=7;XoXKW´%»% W8yû4FY6ÇrC`ë¡qªAqmwlOovóñËS]"á9½G	ùºäE¿!­‘âÚ2WÕmz[7"áãÛY'oOû1­ä—gíÔrnÊnícÁcÔUwóPt.=N+ÕfLU&rGüÁüâóù_­FNdh¡sqm½zÔ1F…K/Ú,%péPãY.´;K’Üî0ûS¡­O¡;sÀA§œ
h0éô’_íz]§&%p'ËF(UkàO“D_ñD$


In [33]:
class LayerNorm1d: # (used to be BatchNorm1d)
  
  def __init__(self, dim, eps=1e-5, momentum=0.1):
    self.eps = eps
    self.gamma = torch.ones(dim)
    self.beta = torch.zeros(dim)
  
  def __call__(self, x):
    # calculate the forward pass
    xmean = x.mean(1, keepdim=True) # batch mean
    xvar = x.var(1, keepdim=True) # batch variance
    xhat = (x - xmean) / torch.sqrt(xvar + self.eps) # normalize to unit variance
    self.out = self.gamma * xhat + self.beta
    return self.out
  
  def parameters(self):
    return [self.gamma, self.beta]

torch.manual_seed(1337)
module = LayerNorm1d(100)
x = torch.randn(32, 100) # batch size 32 of 100-dimensional vectors
x = module(x)
x.shape

torch.Size([32, 100])

In [34]:
import torch
import torch.nn as nn
from torch.nn import functional as F

# hyperparameters
batch_size = 16 # how many independent sequences will we process in parallel?
block_size = 32 # what is the maximum context length for predictions?
max_iters = 120000
eval_interval = 100
learning_rate = 1e-3
device = 'cuda' if torch.cuda.is_available() else 'cpu'
eval_iters = 200
n_embd = 64
n_head = 4
n_layer = 4
dropout = 0.0
# ------------

torch.manual_seed(1337)

import nltk
nltk.download('machado')
from nltk.corpus import machado
text=machado.raw()

# here are all the unique characters that occur in this text
chars = sorted(list(set(text)))
vocab_size = len(chars)
# create a mapping from characters to integers
stoi = { ch:i for i,ch in enumerate(chars) }
itos = { i:ch for i,ch in enumerate(chars) }
encode = lambda s: [stoi[c] for c in s] # encoder: take a string, output a list of integers
decode = lambda l: ''.join([itos[i] for i in l]) # decoder: take a list of integers, output a string

# Train and test splits
data = torch.tensor(encode(text), dtype=torch.long)
n = int(0.9*len(data)) # first 90% will be train, rest val
train_data = data[:n]
val_data = data[n:]

# data loading
def get_batch(split):
    # generate a small batch of data of inputs x and targets y
    data = train_data if split == 'train' else val_data
    ix = torch.randint(len(data) - block_size, (batch_size,))
    x = torch.stack([data[i:i+block_size] for i in ix])
    y = torch.stack([data[i+1:i+block_size+1] for i in ix])
    x, y = x.to(device), y.to(device)
    return x, y

@torch.no_grad()
def estimate_loss():
    out = {}
    model.eval()
    for split in ['train', 'val']:
        losses = torch.zeros(eval_iters)
        for k in range(eval_iters):
            X, Y = get_batch(split)
            logits, loss = model(X, Y)
            losses[k] = loss.item()
        out[split] = losses.mean()
    model.train()
    return out

class Head(nn.Module):
    """ one head of self-attention """

    def __init__(self, head_size):
        super().__init__()
        self.key = nn.Linear(n_embd, head_size, bias=False)
        self.query = nn.Linear(n_embd, head_size, bias=False)
        self.value = nn.Linear(n_embd, head_size, bias=False)
        self.register_buffer('tril', torch.tril(torch.ones(block_size, block_size)))

        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        B,T,C = x.shape
        k = self.key(x)   # (B,T,C)
        q = self.query(x) # (B,T,C)
        # compute attention scores ("affinities")
        wei = q @ k.transpose(-2,-1) * C**-0.5 # (B, T, C) @ (B, C, T) -> (B, T, T)
        wei = wei.masked_fill(self.tril[:T, :T] == 0, float('-inf')) # (B, T, T)
        wei = F.softmax(wei, dim=-1) # (B, T, T)
        wei = self.dropout(wei)
        # perform the weighted aggregation of the values
        v = self.value(x) # (B,T,C)
        out = wei @ v # (B, T, T) @ (B, T, C) -> (B, T, C)
        return out

class MultiHeadAttention(nn.Module):
    """ multiple heads of self-attention in parallel """

    def __init__(self, num_heads, head_size):
        super().__init__()
        self.heads = nn.ModuleList([Head(head_size) for _ in range(num_heads)])
        self.proj = nn.Linear(n_embd, n_embd)
        self.dropout = nn.Dropout(dropout)

    def forward(self, x):
        out = torch.cat([h(x) for h in self.heads], dim=-1)
        out = self.dropout(self.proj(out))
        return out

class FeedFoward(nn.Module):
    """ a simple linear layer followed by a non-linearity """

    def __init__(self, n_embd):
        super().__init__()
        self.net = nn.Sequential(
            nn.Linear(n_embd, 4 * n_embd),
            nn.ReLU(),
            nn.Linear(4 * n_embd, n_embd),
            nn.Dropout(dropout),
        )

    def forward(self, x):
        return self.net(x)

class Block(nn.Module):
    """ Transformer block: communication followed by computation """

    def __init__(self, n_embd, n_head):
        # n_embd: embedding dimension, n_head: the number of heads we'd like
        super().__init__()
        head_size = n_embd // n_head
        self.sa = MultiHeadAttention(n_head, head_size)
        self.ffwd = FeedFoward(n_embd)
        self.ln1 = nn.LayerNorm(n_embd)
        self.ln2 = nn.LayerNorm(n_embd)

    def forward(self, x):
        x = x + self.sa(self.ln1(x))
        x = x + self.ffwd(self.ln2(x))
        return x

# super simple bigram model
class BigramLanguageModel(nn.Module):

    def __init__(self):
        super().__init__()
        # each token directly reads off the logits for the next token from a lookup table
        self.token_embedding_table = nn.Embedding(vocab_size, n_embd)
        self.position_embedding_table = nn.Embedding(block_size, n_embd)
        self.blocks = nn.Sequential(*[Block(n_embd, n_head=n_head) for _ in range(n_layer)])
        self.ln_f = nn.LayerNorm(n_embd) # final layer norm
        self.lm_head = nn.Linear(n_embd, vocab_size)

    def forward(self, idx, targets=None):
        B, T = idx.shape

        # idx and targets are both (B,T) tensor of integers
        tok_emb = self.token_embedding_table(idx) # (B,T,C)
        pos_emb = self.position_embedding_table(torch.arange(T, device=device)) # (T,C)
        x = tok_emb + pos_emb # (B,T,C)
        x = self.blocks(x) # (B,T,C)
        x = self.ln_f(x) # (B,T,C)
        logits = self.lm_head(x) # (B,T,vocab_size)

        if targets is None:
            loss = None
        else:
            B, T, C = logits.shape
            logits = logits.view(B*T, C)
            targets = targets.view(B*T)
            loss = F.cross_entropy(logits, targets)

        return logits, loss

    def generate(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx
    def generate_final(self, idx, max_new_tokens):
        # idx is (B, T) array of indices in the current context
        for _ in range(max_new_tokens):
            # crop idx to the last block_size tokens
            idx_cond = idx[:, -block_size:]
            # get the predictions
            logits, loss = self(idx_cond)
            # focus only on the last time step
            logits = logits[:, -1, :] # becomes (B, C)
            # apply softmax to get probabilities
            probs = F.softmax(logits, dim=-1) # (B, C)
            # sample from the distribution
            idx_next = torch.argmax(probs).view([1,1])
            # append sampled index to the running sequence
            idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
        return idx

model = BigramLanguageModel()
m = model.to(device)
# print the number of parameters in the model
print(sum(p.numel() for p in m.parameters())/1e6, 'M parameters')

# create a PyTorch optimizer
optimizer = torch.optim.AdamW(model.parameters(), lr=learning_rate)

for iter in range(max_iters):

    # every once in a while evaluate the loss on train and val sets
    if iter % eval_interval == 0 or iter == max_iters - 1:
        losses = estimate_loss()
        print(f"step {iter}: train loss {losses['train']:.4f}, val loss {losses['val']:.4f}")

    # sample a batch of data
    xb, yb = get_batch('train')

    # evaluate the loss
    logits, loss = model(xb, yb)
    optimizer.zero_grad(set_to_none=True)
    loss.backward()
    optimizer.step()

# generate from the model
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))


[nltk_data] Downloading package machado to /root/nltk_data...
[nltk_data]   Package machado is already up-to-date!


0.220307 M parameters
step 0: train loss 5.2092, val loss 5.2124
step 100: train loss 2.6881, val loss 2.8650
step 200: train loss 2.5287, val loss 2.6908
step 300: train loss 2.4631, val loss 2.6037
step 400: train loss 2.4085, val loss 2.5562
step 500: train loss 2.3622, val loss 2.5132
step 600: train loss 2.2941, val loss 2.4093
step 700: train loss 2.2577, val loss 2.3856
step 800: train loss 2.2295, val loss 2.3596
step 900: train loss 2.1980, val loss 2.3245
step 1000: train loss 2.1836, val loss 2.2906
step 1100: train loss 2.1533, val loss 2.2548
step 1200: train loss 2.1311, val loss 2.2709
step 1300: train loss 2.1132, val loss 2.2251
step 1400: train loss 2.0820, val loss 2.1964
step 1500: train loss 2.0621, val loss 2.1777
step 1600: train loss 2.0427, val loss 2.1612
step 1700: train loss 2.0286, val loss 2.1643
step 1800: train loss 2.0177, val loss 2.1460
step 1900: train loss 2.0086, val loss 2.1315
step 2000: train loss 2.0069, val loss 2.1302
step 2100: train loss 1.

In [35]:
context = torch.zeros((1, 1), dtype=torch.long, device=device)
print(decode(m.generate(context, max_new_tokens=2000)[0].tolist()))

	ingulamente.

— Parecia daquela história.

Resisteve não a
  vista
enfermar
a Preladura teveu poder, uso; entre a que a hiês insultante que sobre a terra que experiência de um longe: — Mas
desceu meques; confessos
andares os dois...

-- Não lá se compõe em satisfance. A verdade,
agora entendeu a maral e criança...

As diplomáticas d'....

         Desse sunho? E
     maior nenhuma, apmassado então. Não
posso que ânimo foi
estes estrelam-se e as divinais deixoundo. Tal
  relação secreto, que o
solículo sorria, em cena nela amanhã...
pensando o meio dos sentimentos e vós, aos
sobretudos sorriu-se deu-lhe ao colegas).

— É dispos,
jovens exemplar como o mais mais sócinos espécies apreciada. Trazia ela
que oito dizer que o passo que pode adoecer na pretendente e de morto, nada quinzena: é dia dois da designificar...

Deus se sentara vergonhas e rapleens e anos espereceu os olcantos à mania, que você disseram com os estremeceu assim dois tamos de nencentes. Que
  mandaria? perguntei ela.



In [36]:
torch.save(model.state_dict(), 'model.pth')